games:
  - id: seeded-web-trunk
    name: DCSS trunk, custom seed
    crawl_binary: ./crawl
    rcfile_path: ./rcs/
    macro_path: ./rcs/
    morgue_path: ./rcs/%n
    inprogress_path: ./rcs/running
    ttyrec_path: ./rcs/ttyrecs/%n
    socket_path: ./rcs
    client_path: ./webserver/game_data/
    # dir_path: .
    # cwd: .
    morgue_url: None
    send_json_options: True
    options:
      - -seed
    # env:
    #   LANG: en_US.UTF8
  - id: sprint-web-trunk
    name: Sprint trunk
    crawl_binary: ./crawl
    rcfile_path: ./rcs/
    macro_path: ./rcs/
    morgue_path: ./rcs/%n
    inprogress_path: ./rcs/running
    ttyrec_path: ./rcs/ttyrecs/%n
    socket_path: ./rcs
    client_path: ./webserver/game_data/
    # dir_path: .
    # cwd: .
    morgue_url: None
    send_json_options: True
    options:
      - -sprint
    # env:
    #   LANG: en_US.UTF8
  - id: tut-web-trunk
    name: Tutorial trunk
    crawl_binary: ./crawl
    rcfile_path: ./rcs/
    macro_path: ./rcs/
    morgue_path: ./rcs/%n
    inprogress_path: ./rcs/running
    ttyrec_path: ./rcs/ttyrecs/%n
    socket_path: ./rcs
    client_path: ./webserver/game_data/
    # dir_path: .
    # cwd: .
    morgue_url: None
    send_json_options: True
    options:
      - -tutorial
    # env:
    #   LANG: en_US.UTF8
